# action.yml
name: 'List Images using Crane'
description: 'List Images using Crane'
inputs:
  location:
    description: "GCP Artifact Repository Location"
    required: true
  project:
    description: 'GCP Project'
    required: true
  repository_list:
    description: "Google Cloud Artifact Repository List"
    required: true
  tag:
    description: "Image Tag"
    required: true
outputs:
  images:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.location }}
    - ${{ inputs.project }}
    - ${{ inputs.repository_list }}
    - ${{ inputs.tag }}
